general.live_config_reload = true

general.import = [
    "~/.config/alacritty/themes/gruvbox.toml"
]

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[env]
TERM = "xterm-256color"

[font]
size = 14.0
builtin_box_drawing = false

[font.normal]
family = "JetBrains Mono NL"
#family = "GoMono Nerd Font Mono"
style = "Normal"
